version: "3.9"
services:
  web:
    build: ./backend
    ports:
      - "8000:5000"
    volumes:
      - ./backend:/code
    environment:
      FLASK_ENV: development
  redis:
    image: "redis:alpine"
